### PR TITLE
Updated for latest laravel changes

### LINKED ISSUE #81: Broken After Taylor Moved The Services And Compiled Files
https://travis-ci.org/BootstrapCMS/Credentials/jobs/54171707

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #81.

### CODE REVIEW

**Comment by crynobone** [comment]
Can you keep the original `.gitignore`. Someone could use the latest testbench with an older Laravel Framework version (locked for whatever reason). Just to be safe.

**Comment by GrahamCampbell** [comment]
Sure. :)

**Comment by GrahamCampbell** [comment]
I'll resend this. It's targeted at the wrong branch, lol.

**Comment by GrahamCampbell** [comment]
@crynobone https://github.com/orchestral/testbench/pull/83.

**Pull request closed without merging**
