### PR TITLE
Support newer laravel versions

### LINKED ISSUE #81: Broken After Taylor Moved The Services And Compiled Files
https://travis-ci.org/BootstrapCMS/Credentials/jobs/54171707

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Replaces #82. Closes #81.

### CODE REVIEW

**Comment by crynobone** [comment]
Thanks.

**Comment by GrahamCampbell** [comment]
np, could we get another release tagged to include this please?

**Comment by crynobone** [comment]
Yeah, in few minutes.

**Comment by GrahamCampbell** [comment]
Thanks.

**Comment by crynobone** [comment]
Done

**Comment by GrahamCampbell** [comment]
:beers:

**Pull request merged**
