### PR TITLE
[6.x] list spatie/laravel-ray as dev dependency

### PR DESCRIPTION
**Pull request by Nielsvanpach**
I think spatie/laravel-ray can be listed as a dev dependency 
(the same applies for the 7.x branch)

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by driesvints** [comment]
Think tbh we can remove the dependency.

**Comment by crynobone** [comment]
No plan to change the requirement, and you can require `orchestra/testbench-core` and configure each requirements manually.

**Comment by GrahamCampbell** [comment]
> list spatie/laravel-ray as dev dependency

I'm not sure I follow why you'd want to do that. Are you getting mixed up with `suggest`?

**Comment by Nielsvanpach** [comment]
> I'm not sure I follow why you'd want to do that. Are you getting mixed up with suggest?

I would guess laravel-ray isn't needed as a required dependency here, unless I'm missing something?

**Comment by driesvints** [comment]
@Nielsvanpach can you restore the branch?

**Comment by Nielsvanpach** [comment]
Done

**Pull request closed without merging**
