### PR TITLE
Add DatabaseMigrationsRealpath Trait

### LINKED ISSUE #121: Migrate:rollback/DatabaseMigrations Trait
I was wondering if their was a reason that rollback was left out of the database commands updated for use with the realpath attribute, and if you had considered implementing something like the DatabaseMigrations trait in Laravel for tests.  (The arguments would have to come from a test class property or getter function.)

I reimplemented the trait for my own use (using migrate:refresh) since migrate:rollback was unavailable.  If you would be interested in them, I could port the trait into testbench and contribute it as a pull request.  If not or if you would rather implement it yourself or have a reason you don't  want it, that's fine.

### PR DESCRIPTION
**Pull request by loren138**
This closes #121.

As it turns out migrate:rollback does not need a realpath attribute so I did not do that.  Since the DatabaseMigrations trait was already pulled in from Laravel, I created a new trait call DatabaseMigartionsRealpath.  To use this trait the user must create a function like the one below

    protected function getMigrationsRealpath()
    {
        return realpath(__DIR__.'/migrations');
    }

Also, please merge this into 3.3.  I did not include this for 3.1 since that branch did not have any of the standard laravel traits enabled yet.  I can create a separate pull for 3.1 if that is desired.

### CODE REVIEW

**Comment by crynobone** [comment]
> As it turns out migrate:rollback does not need a realpath attribute so I did not do that.

So therefore there no real need to have this PR?

> Also, please merge this into 3.3

Laravel 5.3 introduce `ServiceProvider::loadMigrationsFrom()` helpers. The `--realpath` would no longer be needed from now forward.

**Comment by crynobone** [comment]
I'm okay if we want to look at adding something such as 

```php
$this->loadMigrationsFrom($path);
```

and have the following method:

```php
    /**
     * Define hooks to migrate the database before and after each test.
     *
     * @param  string  $realpah
     * @return void
     */
    public function loadMigrationsFrom($realpath)
    {
        $this->artisan('migrate', [
            '--realpath' => $realpath,
        ]);

        $this->beforeApplicationDestroyed(function () {
            $this->artisan('migrate:rollback');
        });
    }
````

There no reason to have a Trait and then have to manually override a method, plus this can be PRed to 3.1

**Comment by loren138** [comment]
Ah, I like that code.  I really didn't like the override, but since it was a function their was no way to use it from an env var.

I'll make a new PR.

**Comment by loren138** [comment]
The one downside to that is that the override function can be done in TestCase.php in the project.  Then any files the need migrations would be given the trait and would have migrations run.  In this method, you'd need to override setup in each test class that needs migrations and either include the migrations path there or call a similar function in the parent testcase.

This method is cleaner for new adopters though.

**Pull request closed without merging**
