### PR TITLE
[4.x] Do not pin laravel to a specific release

### PR DESCRIPTION
**Pull request by ericp-mrel**

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
👎 That version of Laravel is required because it is genuinely needed.

**Comment by ericp-mrel** [comment]
Sorry if I'm missing something, but why is that specific version of laravel needed?

**Comment by GrahamCampbell** [comment]
Used here: https://github.com/orchestral/testbench/commit/c7a047a7ff8f7052d2e5f5478a42b53856cb1c74.

**Comment by GrahamCampbell** [comment]
> Sorry if I'm missing something, but why is that specific version of laravel needed?

It is "at least" that version. This allows any 6.x version at least as new as that.

**Pull request closed without merging**
